# TCL File Generated by Component Editor 9.1sp2
# Sun Feb 12 09:46:12 CST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | ava_alu "ava_alu" v1.0
# | dxzhang@ustc.edu 2012.02.12.09:46:12
# | ava_alu module
# | 
# | F:/dsd/SOPC_de2-70/DE2_70_NET_alu/IP/ava_alu/ava_alu.v
# | 
# |    ./ava_alu.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 9.1
# | 
package require -exact sopc 9.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module ava_alu
# | 
set_module_property DESCRIPTION "ava_alu module"
set_module_property NAME ava_alu
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property GROUP Accelerators
set_module_property AUTHOR dxzhang@ustc.edu
set_module_property DISPLAY_NAME ava_alu
set_module_property TOP_LEVEL_HDL_FILE ava_alu.v
set_module_property TOP_LEVEL_HDL_MODULE ava_alu
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file ava_alu.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter OP_ADD STD_LOGIC_VECTOR 1
set_parameter_property OP_ADD DEFAULT_VALUE 1
set_parameter_property OP_ADD DISPLAY_NAME OP_ADD
set_parameter_property OP_ADD UNITS None
set_parameter_property OP_ADD ALLOWED_RANGES 0:15
set_parameter_property OP_ADD DISPLAY_HINT ""
set_parameter_property OP_ADD AFFECTS_GENERATION false
set_parameter_property OP_ADD HDL_PARAMETER true
add_parameter OP_SUB STD_LOGIC_VECTOR 2
set_parameter_property OP_SUB DEFAULT_VALUE 2
set_parameter_property OP_SUB DISPLAY_NAME OP_SUB
set_parameter_property OP_SUB UNITS None
set_parameter_property OP_SUB ALLOWED_RANGES 0:15
set_parameter_property OP_SUB DISPLAY_HINT ""
set_parameter_property OP_SUB AFFECTS_GENERATION false
set_parameter_property OP_SUB HDL_PARAMETER true
add_parameter OP_AND STD_LOGIC_VECTOR 3
set_parameter_property OP_AND DEFAULT_VALUE 3
set_parameter_property OP_AND DISPLAY_NAME OP_AND
set_parameter_property OP_AND UNITS None
set_parameter_property OP_AND ALLOWED_RANGES 0:15
set_parameter_property OP_AND DISPLAY_HINT ""
set_parameter_property OP_AND AFFECTS_GENERATION false
set_parameter_property OP_AND HDL_PARAMETER true
add_parameter OP_OR STD_LOGIC_VECTOR 4
set_parameter_property OP_OR DEFAULT_VALUE 4
set_parameter_property OP_OR DISPLAY_NAME OP_OR
set_parameter_property OP_OR UNITS None
set_parameter_property OP_OR ALLOWED_RANGES 0:15
set_parameter_property OP_OR DISPLAY_HINT ""
set_parameter_property OP_OR AFFECTS_GENERATION false
set_parameter_property OP_OR HDL_PARAMETER true
add_parameter OP_XOR STD_LOGIC_VECTOR 5
set_parameter_property OP_XOR DEFAULT_VALUE 5
set_parameter_property OP_XOR DISPLAY_NAME OP_XOR
set_parameter_property OP_XOR UNITS None
set_parameter_property OP_XOR ALLOWED_RANGES 0:15
set_parameter_property OP_XOR DISPLAY_HINT ""
set_parameter_property OP_XOR AFFECTS_GENERATION false
set_parameter_property OP_XOR HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point ava
# | 
add_interface ava avalon end
set_interface_property ava addressAlignment DYNAMIC
set_interface_property ava associatedClock clock_reset
set_interface_property ava burstOnBurstBoundariesOnly false
set_interface_property ava explicitAddressSpan 0
set_interface_property ava holdTime 0
set_interface_property ava isMemoryDevice false
set_interface_property ava isNonVolatileStorage false
set_interface_property ava linewrapBursts false
set_interface_property ava maximumPendingReadTransactions 0
set_interface_property ava printableDevice false
set_interface_property ava readLatency 0
set_interface_property ava readWaitTime 1
set_interface_property ava setupTime 0
set_interface_property ava timingUnits Cycles
set_interface_property ava writeWaitTime 0

set_interface_property ava ASSOCIATED_CLOCK clock_reset
set_interface_property ava ENABLED true

add_interface_port ava ava_chipselect chipselect Input 1
add_interface_port ava ava_address address Input 2
add_interface_port ava ava_read read Input 1
add_interface_port ava ava_write write Input 1
add_interface_port ava ava_readdata readdata Output 32
add_interface_port ava ava_writedata writedata Input 32
add_interface_port ava ava_byteenable byteenable Input 4
add_interface_port ava ava_waitrequest waitrequest Output 1
# | 
# +-----------------------------------
