#ifndef __NIOS2_SYSTEM_H__
#define __NIOS2_SYSTEM_H__


/*
 * This file contains hardware information about the target platform.
 *
 * This file is automatically generated.  Do not modify.
 */
   
/* Input System: DE2_70_SOPC */
/* Target CPU: cpu */

/* Nios II Constants */
#define NIOS2_STATUS_PIE_MSK  0x1
#define NIOS2_STATUS_PIE_OFST 0
#define NIOS2_STATUS_U_MSK    0x2
#define NIOS2_STATUS_U_OFST   1

/*
 * Outputting basic values from system.ptf.
 */

#define na_sdram_u1                                           0000000000
#define na_sdram_u1_size                                      0x02000000
#define na_sdram_u1_end                                       0x02000000
#define na_sdram_u1_clock_freq                                 100000000
#define na_cfi_flash                                          0x08800000
#define na_cfi_flash_size                                     0x00800000
#define na_cfi_flash_end                                      0x09000000
#define na_cfi_flash_clock_freq                                100000000
#define na_sysid                                              0x020010a0
#define na_sysid_clock_freq                                    100000000
#define na_uart                                               0x02001040
#define na_uart_irq                                                    4
#define na_uart_clock_freq                                     100000000
#define na_pll                                                0x02001060
#define na_pll_clock_freq                                       50000000
#define na_tristate_bridge_flash_clock_freq                      100000000
#define na_DM9000A                                            0x020010a8
#define na_DM9000A_irq                                                 1
#define na_DM9000A_clock_freq                                   25000000
#define na_timer                                              0x02001080
#define na_timer_irq                                                   2
#define na_timer_clock_freq                                    100000000
#define na_timer_stamp                                        0x02001000
#define na_timer_stamp_irq                                             3
#define na_timer_stamp_clock_freq                              100000000
#define na_epcs_flash_controller                              0x09000000
#define na_epcs_flash_controller_size                         0x00000800
#define na_epcs_flash_controller_end                          0x09000800
#define na_epcs_flash_controller_irq                                   5
#define na_epcs_flash_controller_clock_freq                      100000000
#define na_ava_alu_0                                          0x02000000
#define na_ava_alu_0_clock_freq                                100000000

/* Executing ...scripts/nios2.h/altera_avalon_sysid.pm */

/* No translation necessary for sysid */

/* Executing ...scripts/nios2.h/altera_avalon_uart.pm */

/* Redefining uart -> uart0 */
#undef na_uart
#undef na_uart_irq

#define na_uart0                                  ((void **) 0x02001040)
#define na_uart0_irq                                                   4

/* The default uart is always the first one found in the PTF file */
#define nasys_printf_uart na_uart0

/* Executing ...scripts/nios2.h/no_legacy_module.pm */
/* Executing ...scripts/nios2.h/altera_avalon_timer.pm */

/* system timer input clock frequency */
#define nasys_clock_freq                                       100000000
#define nasys_clock_freq_1000                                     100000

/* Redefining timer -> timer0 */
#undef na_timer
#undef na_timer_irq

#define na_timer0                                  ((void *) 0x02001080)
#define na_timer0_irq                                                  2

/*
 * Basic System Information
 */
#define nasys_icache_size                                           4096
#define nasys_icache_line_size                                        32
#define nasys_dcache_size                                           2048
#define nasys_dcache_line_size                                        32

#define nasys_program_mem                                    na_sdram_u1
#define nasys_program_mem_size                          na_sdram_u1_size
#define nasys_program_mem_end                            na_sdram_u1_end


#define na_cpu_clock_freq                                      100000000
#define CPU_RESET_ADDRESS                                     0x08800000
#define CPU_EXCEPT_ADDRESS                                    0x00000020

#endif /* __NIOS2_H__ */
